"""Add owner_id and name to games

Revision ID: 246707c703b3
Revises: 6a1f2e1926df
Create Date: 2026-01-07 12:55:07.140659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246707c703b3'
down_revision = '6a1f2e1926df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'players', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('name')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
