"""Add device_id to players

Revision ID: 6a1f2e1926df
Revises: a58032ece895
Create Date: 2026-01-07 12:17:02.703314

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = '6a1f2e1926df'
down_revision = 'a58032ece895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add device_id column as nullable first
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=255), nullable=True))
    
    # Step 2: Generate device IDs for existing players
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM players WHERE device_id IS NULL"))
    for row in result:
        player_id = row[0]
        # Generate a unique device ID for each existing player
        device_id = f"migrated-{uuid.uuid4()}"
        connection.execute(
            sa.text("UPDATE players SET device_id = :device_id WHERE id = :player_id"),
            {"device_id": device_id, "player_id": player_id}
        )
    
    # Step 3: Make device_id non-nullable and unique
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('device_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_players_device_id'), ['device_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_device_id'))
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###
