"""Allow duplicate usernames

Revision ID: a58032ece895
Revises: 698b3a8a6b75
Create Date: 2025-12-09 15:07:47.035203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58032ece895'
down_revision = '698b3a8a6b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_username'))
        batch_op.create_index(batch_op.f('ix_players_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_username'))
        batch_op.create_index(batch_op.f('ix_players_username'), ['username'], unique=True)

    # ### end Alembic commands ###
